'use client';

import { useLanguage } from '@/lib/i18n/context';
import { AlertTriangle } from 'lucide-react';

export default function DisclaimerPage() {
  const { language } = useLanguage();

  return (
    <div className="min-h-screen py-12 px-4 sm:px-6 max-w-3xl mx-auto text-gray-300 text-sm leading-relaxed">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-xl bg-amber-500/10 border border-amber-500/30 flex items-center justify-center text-amber-400">
          <AlertTriangle className="w-5 h-5" />
        </div>
        <h1 className="text-3xl font-black text-white font-heading">
          {language === 'hi' ? 'वैधानिक ज्योतिष अस्वीकरण' : 'Astrology Disclaimer'}
        </h1>
      </div>

      <div className="space-y-6 bg-navy-900 border border-navy-800 rounded-3xl p-6 sm:p-8">
        <section>
          <h2 className="text-base font-bold text-white mb-2 font-heading">
            {language === 'hi' ? '1. सूचनात्मक एवं आत्म-चिंतन का उद्देश्य' : '1. Informational & Reflective Purpose'}
          </h2>
          <p>
            {language === 'hi'
              ? 'एस्ट्रोकंसल्ट द्वारा प्रदान किया गया ज्योतिषीय विश्लेषण, ग्रह-दशा गणना और जन्म कुंडली रिपोर्ट केवल सूचना, आत्म-चिंतन और व्यक्तिगत मार्गदर्शन के लिए है। ज्योतिष प्रतीकात्मक प्रवृत्तियों और समय-चक्रों का एक प्राचीन दार्शनिक अध्ययन है।'
              : 'Astrological consultations, planetary calculations, and Kundli reports generated by AstroConsult are provided strictly for informational, educational, and personal self-reflection purposes. Astrology represents an ancient philosophical and symbolic system of archetypal tendencies and cyclical timing patterns.'}
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-white mb-2 font-heading">
            {language === 'hi' ? '2. कोई अंधविश्वास या अचूक भविष्यफल का दावा नहीं' : '2. No Supernatural Guarantees or Fatalistic Claims'}
          </h2>
          <p>
            {language === 'hi'
              ? 'एस्ट्रोकंसल्ट किसी भी प्रकार के 100% अचूक भविष्यवाणियों, चमत्कारी परिणामों या सुनिश्चित घटनाओं का दावा नहीं करता। हम किसी निश्चित लॉटरी, चमत्कारिक विवाह या अचानक धन लाभ की गारंटी नहीं देते। आपका कर्म, स्वतंत्र संकल्प और निर्णय ही आपके भविष्य को आकार देते हैं।'
              : 'AstroConsult explicitly disclaims any claims of 100% predictive accuracy, absolute certainty, or guaranteed life events. We do NOT guarantee specific financial gains, job acquisitions, marriages, lottery wins, or miraculous outcomes. You retain total free will, autonomy, and personal responsibility for all decisions and actions taken in your life.'}
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-white mb-2 font-heading">
            {language === 'hi' ? '3. चिकित्सा, कानूनी या वित्तीय सलाह का विकल्प नहीं' : '3. Not Professional Medical, Legal, or Financial Advice'}
          </h2>
          <p>
            {language === 'hi'
              ? 'ज्योतिषीय रिपोर्ट किसी प्रमाणित चिकित्सक, मनोरोग विशेषज्ञ, वकील या वित्तीय सलाहकार की सलाह का विकल्प नहीं है। गंभीर स्वास्थ्य, कानूनी या वित्तीय निर्णयों के लिए हमेशा योग्य और अधिकृत विशेषज्ञों से परामर्श लें।'
              : 'Astrological readings must never be utilized as a substitute for professional diagnosis, therapy, legal counsel, or certified financial advice. If you are experiencing medical illness, psychiatric distress, legal disputes, or severe financial decisions, consult qualified and licensed professionals.'}
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-white mb-2 font-heading">
            {language === 'hi' ? '4. नैतिक मार्गदर्शन की प्रतिबद्धता' : '4. Commitment to Ethical Guidance'}
          </h2>
          <p>
            {language === 'hi'
              ? 'हम डर फैलाने, दोषों के नाम पर शोषण करने या अंधविश्वास को बढ़ावा देने का कड़ा विरोध करते हैं। हमारा उद्देश्य आपको आत्म-विश्वास, स्पष्टता और व्यावहारिक विवेक प्रदान करना है।'
              : 'We strictly forbid fear-based selling, superstition exploitation, or dosha scare tactics. Our goal is to provide respectful, uplifting, and practical insights that help you understand your temperament and optimize your potential.'}
          </p>
        </section>
      </div>
    </div>
  );
}
